### ISSUE TITLE
--no-cache CLI flag

### ISSUE THREAD

**Issue by hasparus** [piglovesyou/graphql-let#336]
Hi :wave: 

Possibility to ignore the cache without removing it would be quite useful.
I'm writing a codegen plugin, and I've removed my cache dir about a hundred times already :D

**Comment by piglovesyou** [comment]
@hasparus Hi! Sounds good. I'll merge if given a PR.

A small concern: if the purpose of the option is very much an edge case, users seeing our documentation might be confused. But "This is mainly for development or debugging purpose." would be enough explanation.

**Comment by piglovesyou** [comment]
Here's another reason for how we should not implement `--no-cache`. Let's say we have 100 GraphQL documents and use our webpack loader. In the docs, I recommend executing the `graphql-let` CLI before starting `webpack serve`.

* On CLI, it executes codegen once and tsc once for 100 GraphQL documents
* On `webpack serve`, no codegen and no tsc run thanks to caching 

However, without caching, it can go extremely slow, because each loader context is separated and cannot (should not) be handled at once.

* (No caching with CLI)
* On `webpack serve`, 100 codegen and 100 tsc for 100 GraphQL documents

If we implement `--no-cache`, we let users experience this, which must definitely be unacceptable for them. I know the issuer regards it for debugging purposes, it's good to avoid misleading options.

**Comment by hasparus** [comment]
Fair point, it's better not to include footguns. I'll close the issue.
