### ISSUE TITLE
Babel macro

### ISSUE THREAD

**Issue by sbking** [piglovesyou/graphql-let#349]
Would it be possible to create a babel macro for [babel-plugin-macros](https://github.com/kentcdodds/babel-plugin-macros/blob/main/other/docs/author.md)? This would allow graphql-let to be used in create-react-app projects without ejecting, and possibly other projects where babel macros are available but changing the babel config is not desirable/possible.

**Comment by piglovesyou** [comment]
Hello, @sbking. Interesting. We're discussing [the best way to integrate graphql-let to create-react-app](https://github.com/piglovesyou/graphql-let/issues/317) and your idea is one smart candidate. "Without ejecting" is what we should insist on.

My understanding (I have poor create-react-app experience):

* `graphql-let/babel` needs ejecting to setup babelrc in create-react-app.
* If `graphql-let/gql.macro`, it works without ejecting, since [create-react-app includes `babel-plugin-macros` originally.](https://github.com/facebook/create-react-app/blob/e63de79cc4530efc7402e38923d875f27cdef0c3/packages/babel-preset-react-app/create.js#L117)

[I considered it once, actually](https://twitter.com/piglovesyou1/status/1282871587058769922). We should work on it, then?

**Comment by piglovesyou** [comment]
Please try [v0.17.0](https://github.com/piglovesyou/graphql-let/releases/tag/v0.17.0).
