### ISSUE TITLE
Duplicate named .graphql files intermittently don't generate

### ISSUE THREAD

**Issue by freshollie** [piglovesyou/graphql-let#82]
Hey, thanks for this project!

I'm just starting to integrate this into my project, and I've found that my previous naming convention doesn't work properly when rerunning generation.

I split my queries and mutations into different folders, but it seems that doing this causes only the types for 1 or the other to be generated, and it seems the behaviour is intermittent. 

`./mutations/Device.graphql` and `./queries/Device.graphql` only generates a single `Device.graphql{hash}.d.ts` file some of the time.

Is this something you know about? I was expecting the `hash` to stop this from happening and to write both files and let typescript do the merging.

**Comment by freshollie** [comment]
Ignore this!

**Comment by freshollie** [comment]
Ok. I'm not going mad, there is some race condition going on when generating files:

```bash
MLTHB60928:betaflight-configurator oliver.bell$ yarn codegen
yarn run v1.16.0
$ graphql-codegen --config codegen.yml && graphql-let
  ✔ Parse configuration
  ✔ Generate outputs
[ graphql-let ] 4 .d.ts were generated in packages/configurator/src/gql/__generated__/types.
✨  Done in 30.27s.
MLTHB60928:betaflight-configurator oliver.bell$ yarn codegen
yarn run v1.16.0
$ graphql-codegen --config codegen.yml && graphql-let
  ✔ Parse configuration
  ✔ Generate outputs
[ graphql-let ] 5 .d.ts were generated in packages/configurator/src/gql/__generated__/types.
✨  Done in 15.68s.
MLTHB60928:betaflight-configurator oliver.bell$ yarn codegen
yarn run v1.16.0
$ graphql-codegen --config codegen.yml && graphql-let
  ✔ Parse configuration
  ✔ Generate outputs
[ graphql-let ] 3 .d.ts were generated in packages/configurator/src/gql/__generated__/types.
✨  Done in 19.80s.
MLTHB60928:betaflight-configurator oliver.bell$ yarn codegen
yarn run v1.16.0
$ graphql-codegen --config codegen.yml && graphql-let
  ✔ Parse configuration
  ✔ Generate outputs
[ graphql-let ] 6 .d.ts were generated in packages/configurator/src/gql/__generated__/types.
✨  Done in 26.27s.
MLTHB60928:betaflight-configurator oliver.bell$ yarn codegen
yarn run v1.16.0
$ graphql-codegen --config codegen.yml && graphql-let
  ✔ Parse configuration
  ✔ Generate outputs
[ graphql-let ] 3 .d.ts were generated in packages/configurator/src/gql/__generated__/types.
✨  Done in 21.13s.
MLTHB60928:betaflight-configurator oliver.bell$
```

My graphql files did not change during these executions.

**Comment by freshollie** [comment]
Seems deleting the `__generated__` directories makes it more consistent: 

```bash
MLTHB60928:betaflight-configurator oliver.bell$ yarn codegen
yarn run v1.16.0
$ yarn codegen:clean && graphql-codegen --config codegen.yml && graphql-let
$ rimraf packages/*/src/**/__generated__
  ✔ Parse configuration
  ✔ Generate outputs
[ graphql-let ] 7 .d.ts were generated in packages/configurator/src/gql/__generated__/types.
✨  Done in 51.86s.
MLTHB60928:betaflight-configurator oliver.bell$ yarn codegen
yarn run v1.16.0
$ yarn codegen:clean && graphql-codegen --config codegen.yml && graphql-let
$ rimraf packages/*/src/**/__generated__
  ✔ Parse configuration
  ✔ Generate outputs
[ graphql-let ] 7 .d.ts were generated in packages/configurator/src/gql/__generated__/types.
✨  Done in 49.07s.
MLTHB60928:betaflight-configurator oliver.bell$ 
```

**Comment by piglovesyou** [comment]
Hi @freshollie , thanks for creating this issue. Yes, that's exactly a known restriction, or a  bug, that I should have documented.

This is because generated types contain `declare module '*/Device.graphql'` so it can point to only one of the files named the same.

----

Let's figure out how to solve this, where I don't have a perfect solution yet.

## a. Merging contents

This is good, but it could break the result in this case:

* A document 1 has `query Baa { query1 }`
* A document 2 has `query Baa { query2 }`

They will create a function named the same `useBaaQuery` but returning different results. It's not perfect, but I admit this is way better than the current behavior😅

## b. Generating `Device.graphql.d.ts` as a sibling of `Device.graphql`

This might be our option.

**Pros:**

* It allows users to import `Device.graphql` per `*.graphql` files. No conflict, no merging.
* It could lead more intuitive since the location of the declaration is more obvious than `__generated__`.

**Cons:**

* Another line in `.gitignore` needed such as `*.graphql.d.ts`
* It makes the users' source folder mess.

Plus, filename can't have hash anymore, so we have to have it in its content.

----

Actually the initial architecture was the latter one. I turned it to the current state just since it seems cleaner. I've been waiting for discussing with you😄

**Comment by freshollie** [comment]
These all make sense to me. I actually like the generated directory, because it stays consistent with codegen for me. 

Because I am using codegen, it doesn't let me name any documents the same, so the first option works fine.

Is there any reason why deleting the `__generated__` directory before generating the types makes it consistently generate all the files? This is what I have been doing with n ossies.

---
Just a little feedback btw. I don't use this library for the webpack loader, as I found it was much simpler to use the library to generate the ability to "import" from graphql files, and then when compiling point back towards the main `__generated__/index.tsx` file: 

https://github.com/freshollie/fresh-configurator/blob/0bed3a0dae2ea0c86d10c786ea972576f980e1e1/packages/configurator/webpack.config.js#L62

This way also meant I just pointing my `*.graphql` imports to my `__generated__/index.tsx` for tests too: 

https://github.com/freshollie/fresh-configurator/blob/0bed3a0dae2ea0c86d10c786ea972576f980e1e1/packages/configurator/jest.config.js#L16

I think documenting this usage would be pretty useful for other people using this library, because I couldn't find anything about using this in a testing workflow.

Also, are there any plans to make this into a `graphql-codegen` plugin too? Is that possible? This way the config could sit within my already existing `codegen` chain and generate the definitions instead of having to do them after codegen runs.

**Comment by piglovesyou** [comment]
@freshollie Thank you for the valuable feedback. It's great to discuss that with you. Since you only use graphql-let as a command-line tool, you may not like this change but...

----

I published a tagged release named `graphql-let@canary` including #84. By running `yarn add -D graphql-let@canary`, the following changes occur.

* `a.graphql.d.ts` is generated next to the source file `a.graphql`. This lets you avoid conflict of the same file name. Plus, it fixes #25.
* `__generated__` is now located in the library root (`node_modules/graphql-let`) and stores only `.tsx` . .graphql-let.yml doesn't need to have the `generateDir`  option anymore.

Being a webpack loader is one of the core concepts of graphql-let. I'll use `canary` for my private project for a while and can ship it when it's appropriate. Comments are always welcome.

**Comment by freshollie** [comment]
Cool @piglovesyou, I'm gonna see if the change fits into my current workflow!

**Comment by freshollie** [comment]
@piglovesyou I've switched to `canary` and it's working great in my codebase! I like the change!

**Comment by piglovesyou** [comment]
Thank you, you're so fast! I think I'm going to release it after fixing a few bugs left.
